version: "3.1"
language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
- name: EntitySynonymMapper
- name: ResponseSelector
- name: FallbackClassifier

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
assistant_id: 20240729-223305-faint-solid
